### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by slingamn**

### CODE REVIEW

**Comment by slingamn** [comment]
cc @wader @tpodowd in case [d3b0502](https://github.com/ergochat/readline/pull/3/commits/d3b0502a5f50cc97c6a82272d90090557e99e5e8) or [100f8d0](https://github.com/ergochat/readline/pull/3/commits/100f8d0b89a9af4181500e453e7347b3eb1aa257) pose concerns.

**Comment by slingamn** [comment]
100f8d0b89a9af4181500e453e7347b3eb1aa257 indeed breaks fq. Fix here: https://github.com/wader/fq/pull/612

**Comment by wader** [comment]
@slingamn 👍 and thanks for the fq PR

**Comment by wader** [comment]
@slingamn Should i try cleanup some of my changes and turn into PRs to this repo? possibly these:

[Reduce number of depedencies](https://github.com/wader/readline/commit/15c6283afcb548d8d961eec34667a237c6b1ba9d) - I did this mostly to simplify packaging of fq for distros like debian/ubuntu that vendors all dependecies

[Add ctrl-_ undo support](https://github.com/wader/readline/commit/98dd32046243f03c1e8e330e5ce8c5ab77607d52) - Works ok but don't think it works exactly as gnu readline etc

[Make delete word before first word delete whitespace](https://github.com/wader/readline/commit/837c4650ca8858ad918e014637914c54071a46c3) - Title not very good, what happen before was the deleting word when there was no word the left would delete the whole line

[Changed behaviour of delete key](https://github.com/wader/readline/commit/df96d15cb31fa4414e901602ab5b2f5661636a09) - I also modified this change to fix an issue where the output got ignored after using delete key and there was nothing to delete

**Comment by slingamn** [comment]
I cherry-picked the first of those into this PR as [41156c9](https://github.com/ergochat/readline/pull/3/commits/41156c96cfce299b7eb891e6af7520a601b8b151) :-)

Yeah, send me PRs for anything you want included. My goal is for this fork to ultimately become suitable for use in fq, which means picking up most or all of the fixes that are currently used by fq :-) If you push them to branches in this repository, then we can work on them together if necessary.

**Comment by wader** [comment]
Aha sorry, seems i'm blind :) nice. Ok so just make them build and work on top of the updates branch even if hacky and then polish them. Hopefully will get to it tomorrow or so, feel free to start before if you want.

**Comment by slingamn** [comment]
No rush, you can wait until this branch is merged :-) I'm just giving @tpodowd a few days to chime in.

**Review by tpodowd — APPROVED** [review]
Hi @slingamn - I reviewed the pull request. These changes look good to me. I have not tried my program against them though. It is nice to clean up the confusing `runes` directory and the config init changes look simpler to me. I don't see anything obvious that breaks me.

**Pull request merged**
