### PR TITLE
fix #59

### LINKED ISSUE #59: option-left / alt-left should skip between words
As discussed here: https://github.com/wader/fq/issues/940 this is a normal readline feature. I checked our v0.0.1 (last upstream release) and it does not work there, so it's not a regression, it was never implemented.

### PR DESCRIPTION
**Pull request by slingamn**
Enable "next word" and "previous word" in many terminals:

* Alt-LeftArrow and Alt-RightArrow in xterm and iTerm2 with default settings, where they translate to \x1b\x1b[D and \x1b\x1b[C respectively
* Alt-LeftArrow and Alt-RightArrow in iTerm2 in "Natural text editing mode", where they translate to \x1bb and \x1bf
* Alt-b and Alt-f in xterm, where they translate to \x1bb and \x1bf

### CODE REVIEW

**Comment by slingamn** [comment]
cc @wader , I think this is a general, production-ready fix

**Comment by wader** [comment]
Played around a bit with it in iterm2 and terminal.app both with readline demos and fq and it seems to work 👍

**Review by wader — APPROVED** [review]

**Comment by slingamn** [comment]
Doesn't work in lxterminal, where Alt-LeftArrow and Alt-RightArrow produce `\x1b[1;3D` and `\x1b[1;3C` respectively (???)

**Comment by slingamn** [comment]
The latest patch should fix it in the libvte-based terminals (Gnome Terminal and lxterminal) as well as Windows.

**Comment by slingamn** [comment]
Also works in foot

**Pull request merged**
